version: '3.8'

services:
  mysql-db:
    image: mysql:latest
    container_name: mysql-projeto

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: projeto_db
      MYSQL_USER: familiaeduca
      MYSQL_PASSWORD: projeto

    ports:
      - "3306:3306"

    volumes:
      - mysql_projeto_data:/var/lib/mysql

    restart: unless-stopped

volumes:
  mysql_projeto_data:
